version: '3'

services:
  openhab-crawler:
    image: openhab-crawler:0.0.1-SNAPSHOT
    container_name: openhab-crawler
    restart: unless-stopped
    ports: 
      - 8080:8080

  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana: 
    image: grafana/grafana:7.4.0
    container_name: grafana
    restart: unless-stopped
    environment: 
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=true
    ports: 
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
      
volumes:
  prometheus-data:
  grafana-data: